# Generated by Django 4.1.1 on 2022-09-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_jobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='address_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name=' address_ar'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='address',
            field=models.CharField(max_length=100, verbose_name=' address'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(max_length=50, verbose_name=' project_date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.ImageField(max_length=50, upload_to='', verbose_name=' project_image'),
        ),
    ]
